name: R for Windows Container Images

on:
  push: {}
  workflow_dispatch:
    inputs: {}

jobs:
  docker:
    runs-on: windows-2019
    timeout-minutes: 60
    name: Test for R-${{ matrix.r }}
    strategy:
      fail-fast: false
      matrix:
        r: [ 'release', 'oldrel']

    steps:
      - name: Download image r-windows:${{ matrix.r }}
        run: |
          docker run runiverse/r-windows:${{ matrix.r }} R -e "sessionInfo()"
